### ISSUE TITLE
[New Package]: LinwoodCloud.Butterfly

### ISSUE THREAD

**Issue by CodeDoctorDE** [vedantmgoyal2009/winget-pkgs-automation#191]
### List the PackageIdentifier of the package to be added to automation

LinwoodCloud.Butterfly

### Details about the application

https://github.com/LinwoodCloud/butterfly is the source code of the file.
On every https://github.com/LinwoodCloud/butterfly/releases that starts with a v, is a new release. The asset `Butterfly-Setup.exe` is the file that should be published

**Comment by vedantmgoyal2009** [comment]
@allcontributors please add @CodeDoctorDE for ideas

**Comment by CodeDoctorDE** [comment]
Does it detect, if the tag starts with a v?
I use stable and preview branches to have a persistent url for the website

**Comment by vedantmgoyal2009** [comment]
Yes, when you publish a new release, it will update and a pull request will be created at the winget-pkgs repo.

**Comment by CodeDoctorDE** [comment]
only releases which starts with a `v` should be detected, if I want to have more internal releases, it will also create a pull request on the repo which it shouldn't

**Comment by vedantmgoyal2009** [comment]
No, it shouldn't. Let me explain to you how it works.

First of all, it is defined in the JSON [here](https://github.com/vedantmgoyal2009/winget-pkgs-automation/blob/main/packages/l/linwoodcloud.butterfly.json#L7) that the package is not a pre-release. That's why it will exclude all the pre-releases published in future.

Secondly, automation uses GitHub Release ID and not `tag_name` to detect updates so, for the Stable and Nightly release which you use to have a persistent url for the website, a PR will not be created.
![image](https://user-images.githubusercontent.com/83997633/143682605-41982da6-c380-420c-9f4b-9500717d70cf.png)

And, if you mark "internal releases" as a pre-release, it won't create a PR for them.

**Comment by CodeDoctorDE** [comment]
Thanks! Sorry for this interruption

**Comment by vedantmgoyal2009** [comment]
No problem. Btw, you are the first developer who has directly requested to add his package to automation otherwise all the packages requested are by the community or moderators on the winget-pkgs repo.

**Comment by CodeDoctorDE** [comment]
:tada: 

I searched a way that users can have auto updates and found this repo.
