### ISSUE TITLE
[Feature/Idea]: Postman Collection or Helper Script

### ISSUE THREAD

**Issue by Trenly** [vedantmgoyal2009/winget-pkgs-automation#241]
### What would you like to see changed/added?

It would be nice if there were a postman collection or helper script for manually checking for package updates. Essentially it would be taking all of the packages that have API's for checking their updates and creating a request in postman, then saving that request to the collection and exporting it. The other way to do this would be to have a helper script that users can run to check for updates to a single package manually

**Comment by vedantmgoyal2009** [comment]
Do you mean an additional script should be there so that users can check for updates for an individual package locally?

I don't know about Postman collections so it would take some time for me to get through it. 

Also, I was planning to add functionalities in **@winget-pkgs-automation-bot** so that packages that failed to update can be updated by commenting `/updatepkg` on that package's previous PR. For e.g. vim failed to update in automation, so we can go to https://github.com/microsoft/winget-pkgs/pull/39496 (PR for the previous version of Vim) and comment `/updatepkg` which would automatically create a pull request for the latest version of vim. The only thing is I wanted to know if it will be worth adding this feature to the bot or not.

**Comment by Trenly** [comment]
> Do you mean an additional script should be there so that users can check for updates for an individual package locally?
> 
Yes, exactly
> I don't know about Postman collections so it would take some time for me to get through it.
> 
That's fair. It was just what sparked the idea. I would say either the additional script or a postman collection, probably not both. The script would likely be easier to make
> Also, I was planning to add functionalities in **@winget-pkgs-automation-bot** so that packages that failed to update can be updated by commenting `/updatepkg` on that package's previous PR. For e.g. vim failed to update in automation, so we can go to [microsoft/winget-pkgs#39496](https://github.com/microsoft/winget-pkgs/pull/39496) (PR for the previous version of Vim) and comment `/updatepkg` which would automatically create a pull request for the latest version of vim. The only thing is I wanted to know if it will be worth adding this feature to the bot or not.
>
If it failed the first time, I don't see why it would work the second time, so I don't see a lot of benefit to this

**Comment by vedantmgoyal2009** [comment]
Thanks. I will add the packages and the helper script soon as I get some time.

**Comment by SpecterShell** [comment]
How about [REST Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client)?
