### ISSUE TITLE
New Package: JetBrains.*

### ISSUE THREAD

**Issue by vedantmgoyal9** [vedantmgoyal2009/winget-pkgs-automation#26]
**List the PackageIdentifier of packages to be added to automation**
- Add all JetBrains Products to automation.

Mentioning @jedieaston since he mostly updates JetBrains products.

**Comment by jedieaston** [comment]
Here's the script I use to update most of the JetBrains stuff (not TeamCity/YouTrack/anything EAP, out of laziness more than anything. I still do those manually unless someone catches it first): https://gist.github.com/jedieaston/3b07c5f2fd201bee81fd0a3024d74fdf

It won't work for you out of the box since I hard coded the paths (unless your windows username is easton 👀), and it requires wingethelpers to make commits, but hopefully you can get an idea of how to go through their API response. 

Let me know if you have questions.

**Comment by vedantmgoyal2009** [comment]
Only 1 question, how to get codes for EAP?

Actually, I want to make as many packages automated so that we can focus on other packages in the repo.

**Comment by vedantmgoyal2009** [comment]
@jedieaston All packages (except a few like Rider, ReSharper which I will add when I get time) are now automatically updated. I will look at https://github.com/aaronparker/evergreen/ for more packages that can be added to automation.

**Comment by SpecterShell** [comment]
Please do not replace the host of the URLs. The links on `download.jetbrains.com` can be automatically redirected to the optimal CDN, while those on `download-cdn.jetbrains.com` cannot.
