### ISSUE TITLE
[Bug]: Error while updating

### ISSUE THREAD

**Issue by CodeDoctorDE** [vedantmgoyal2009/winget-pkgs-automation#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```
Write-Error: D:\a\_temp\f90add97-ef6f-498d-a109-0203d199d82c.ps1:2
Line |
   2 |  .\Automation.ps1
     |  ~~~~~~~~~~~~~~~~
     | Error while updating Package LinwoodCloud.Butterfly version 1.2.0


PackageIdentifier : LinwoodCloud.Butterfly
PackageVersion    : 1.2.0
InstallerUrls     : https://github.com/LinwoodCloud/Butterfly/releases/download/v1.2.0/Butterfly-Setup.exe
ReleaseNotesUrl   : https://github.com/LinwoodCloud/Butterfly/releases/tag/v1.2.0
ReleaseDate       : 2022-02-22
YamlCreateParams  : @{SkipPRCheck=False; AutoUpgrade=False; DeletePreviousVersion=False***
```

**Comment by vedantmgoyal2009** [comment]
Actually, there may be times when the pull request is not created immediately if the GitHub API rate limit is exceeded due to number of packages increasing continuously. I'll look into some fix for this but there are some other priorities such as ARP Metadata validation,etc.

Pull request has been created: https://github.com/microsoft/winget-pkgs/pull/47737

**Comment by CodeDoctorDE** [comment]
Thanks, I didn't know that
